[package]
name = "haisvg"
version = "0.1.0"
edition = "2024"
description = "A simple crate for generating on-the-fly svg files"
license = "MIT"
repository = "https://github.com/GitCloneHenry/haisvg"

[dependencies]
